<h1>Hello</h1>
<div data-bind="scope: 'learning_knockoutjs_js_viewmodel'">

    <!-- Render the view model html template file -->
    <div>
        <!-- ko template: 'Learning_KnockoutJs/knockout-template-example' --><!-- /ko -->
    </div>

</div>

<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "learning_knockoutjs_js_viewmodel": {
                    "component": "uiElement",
                    "helloMessage": "Hello from the ViewModel",
                    "goodbyeMessage": "Goodbye from the ViewModel"
                }
            }
        }
    }
}
</script>