<h1>Hello</h1>
<div data-bind="scope: 'learning_knockoutjs_js_viewmodel'">
    <!-- no longer using scope binding -->
    <!--<p data-bind="text:helloMessage"></p>
    <p data-bind="text:goodbyeMessage"></p>-->

    <!-- using Knockout.js Templates instead of scope binding -->
    <!-- this is the tag-less form of Knockout.js -->
    <!-- ko template: "exampleKoTemplateId"--><!-- /ko -->

</div>

<script type="text/html" id="exampleKoTemplateId">
    <h2>Content rendered from a Knockout.js Template</h2>
    <p data-bind="text:helloMessage"></p>
    <p data-bind="text:goodbyeMessage"></p>
</script>

<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "learning_knockoutjs_js_viewmodel": {
                    "component": "uiElement",
                    "helloMessage": "Hello from the ViewModel",
                    "goodbyeMessage": "Goodbye from the ViewModel"
                }
            }
        }
    }
}
</script>